version: "3.7"

services:
  api_rails: &rails
    build: .
    env_file:
      - .env
    environment:
      # - "DATABASE_URL=postgres://postgres:census-dev@postgres:5432/census_production"
      - "DB_HOST=postgres"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  # api_worker:
  #   <<: *rails
  #   command: ["bin/bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
  #   ports: []

  postgres:
    image: postgres:10.7-alpine
    environment:
      POSTGRES_PASSWORD: "census-dev"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  # redis:
  #   image: redis:4.0-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis:/data

volumes:
  gems: {}
  postgres: {}
  # redis: {}
